/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Carousel: typeof import('./components/Setup/Carousel/index.vue')['default']
    CarouselTabs: typeof import('./components/Setup/Carousel/CarouselTabs.vue')['default']
    Create: typeof import('./components/Pages/Resumes/Create.vue')['default']
    CreateModal: typeof import('./components/Pages/Resumes/CreateModal.vue')['default']
    CreateModel: typeof import('./components/Pages/Resumes/CreateModel.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Left: typeof import('./components/Navigations/Main/Left/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Setup: typeof import('./components/Setup/index.vue')['default']
    SetupCarousel: typeof import('./components/Setup/SetupCarousel.vue')['default']
    Tabs: typeof import('./components/Setup/Carousel/Tabs.vue')['default']
  }
}
